<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\FitCore.Application\FitCore.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.15.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Anthropic" Version="12.48.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>
</Project>
